export const operacionalManifest = {
  id: 'operacional' as const,
  name: 'Operacional',
  dependsOn: [] as const,
  alwaysOn: false,
  menu: [
    {
      moduleId: 'operacional',
      permission: 'operacional:view',
      label: 'Agendamentos',
      path: '/dashboard/agendamentos',
      icon: 'CalendarDaysIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:manage_appointments',
      label: 'Agendamentos',
      path: '/dashboard/agendamentos',
      icon: 'CalendarDaysIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:view',
      label: 'Pacientes',
      path: '/dashboard/pacientes',
      icon: 'UsersIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:manage_patients',
      label: 'Pacientes',
      path: '/dashboard/pacientes',
      icon: 'UsersIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:view',
      label: 'Lista de Espera',
      path: '/dashboard/lista-espera',
      icon: 'ClockIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:manage_waitlist',
      label: 'Lista de Espera',
      path: '/dashboard/lista-espera',
      icon: 'ClockIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:view',
      label: 'Dentistas',
      path: '/dashboard/dentistas',
      icon: 'IdentificationIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:manage_catalog',
      label: 'Dentistas',
      path: '/dashboard/dentistas',
      icon: 'IdentificationIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:view',
      label: 'Procedimentos',
      path: '/dashboard/procedimentos',
      icon: 'WrenchScrewdriverIcon',
    },
    {
      moduleId: 'operacional',
      permission: 'operacional:manage_catalog',
      label: 'Procedimentos',
      path: '/dashboard/procedimentos',
      icon: 'WrenchScrewdriverIcon',
    },
  ],
  jobs: ['operacional.reminders'],
};
